### ISSUE TITLE
Ability to paste translation result to frontmost app or copy to clipboard

### ISSUE THREAD

**Issue by ww7** [dev99problems/alfred-translayta#24]
Features request, would be very useful to paste result to clipboard/frontmost app

**Comment by dev99problems** [comment]
Hey 👋  @ww7 , sorry for the late response.

You mean having a translation list and hitting `enter` on one of the options it would be useful to copy it to `clipboard`, did I get you right?

**Comment by dev99problems** [comment]
@ww7 both `copying` and `pasting` landed in [2.1.0](https://github.com/dev99problems/alfred-translayta/releases/tag/v.2.1.0)
